#!/bin/bash

depend_procedure core base

DEFAULTFS="/boot:100:ext2 swap:256:swap /:*:ext4"

worker_intro () {
	inform "MARCH will perform a clean installation. To stop, press Ctrl+C within 10 seconds."
	sleep 10
}


worker_configure ()
{
	var_UI_TYPE="cli"
	ui_init
	HARDWARECLOCK="UTC"
	TIMEZONE="Canada/Pacific"
}

worker_select_source ()
{
	var_PKG_SOURCE_TYPE="net"
	var_SYNC_URL="http://mirrors.kernel.org/archlinux/\$repo/os/\$arch"
}

worker_prepare_disks ()
{
	get_possible_fs && interactive_prepare_disks
}

worker_package_list ()
{
	var_TARGET_PACKAGES="$(grep -v ^# /march/packages.list)"
}


worker_install_packages ()
{
	target_prepare_pacman testing core extra community community-testing && installpkg
}

worker_configure_system () {
	# copy march config
	cp /etc/sudoers $var_TARGET_DIR/etc/
	cp /etc/pacman.d/mirrorlist $var_TARGET_DIR/etc/pacman.d/
	cp /etc/locale.gen $var_TARGET_DIR/etc/
	cp /etc/modprobe.d/modprobe.conf $var_TARGET_DIR/etc/modprobe.d/
	# setup rc.conf
	sed -i -e 's|^DAEMONS=.*|DAEMONS=(dbus networkmanager gdm avahi-daemon cupsd)|' $var_TARGET_DIR/etc/rc.conf
	# adduser and setup locale
	chroot $var_TARGET_DIR locale-gen
	chroot $var_TARGET_DIR usermod -p ZYCnDaw9NK8NI root
	chroot $var_TARGET_DIR useradd -m -p ZYCnDaw9NK8NI -g users -G audio,lp,network,optical,power,storage,video,wheel march
}


worker_set_clock ()
{
	#TODO implement this
	true
}


worker_install_bootloader ()
{
	get_grub_map || return 1
	grub-install $var_GRUB_DEVICE --root-directory=/mnt || return 1
	# check if we have a seperate bootdev (/boot)
	# ToDo: This is double-work, find a better place!
	# See comment in generate_grub_menulst and interactive_grub
	bootdev=$(mount | grep $var_TARGET_DIR/boot | cut -d' ' -f 1)
	generate_grub_menulst || return 1
}
