#!/bin/bash

arg_ui_type="dia"
SOURCE="net"
SYNC_URL="ftp://mirrors.kernel.org/archlinux/\$repo/os/\$arch"

TARGET_PACKAGES="$(grep -v ^# /march/packages.list)"

GRUB_DEVICE="/dev/sda"
PARTITIONS="/dev/sda 100:ext2:+ 512:swap *:ext4"
BLOCKDATA="/dev/sda1 raw no_label ext2;yes;/boot;target;no_opts;no_label;no_params
/dev/sda2 raw no_label swap;yes;no_mountpoint;target;no_opts;no_label;no_params
/dev/sda3 raw no_label ext4;yes;/;target;no_opts;no_label;no_params"

worker_intro ()
{
	notify "March installation may take a while. Have some coffee."
}

worker_configure_system ()
{
	# copy march config
	cp /etc/sudoers $var_TARGET_DIR/etc/
	cp /etc/pacman.d/mirrorlist $var_TARGET_DIR/etc/pacman.d/
	cp /etc/locale.gen $var_TARGET_DIR/etc/
	cp /etc/modprobe.d/modprobe.conf $var_TARGET_DIR/etc/modprobe.d/
	# setup rc.conf
	sed -i -e "s|^DAEMONS=.*|DAEMONS=(dbus networkmanager gdm avahi-daemon cupsd)|" $var_TARGET_DIR/etc/rc.conf
	# adduser and setup locale
	target_locale-gen
	chroot $var_TARGET_DIR usermod -p ZYCnDaw9NK8NI root
	chroot $var_TARGET_DIR useradd -m -p ZYCnDaw9NK8NI -g users -G audio,lp,network,optical,power,storage,video,wheel march
	notify "March configured successfully."
}

worker_msg_report ()
{
	notify $(show_report)
}
