#!/bin/bash

sai_config() {
	say "$FUNCNAME: March customized"
	if [ ! -f /tmp/$FUNCNAME ]; then
		# copy march config
		cp /etc/sudoers /mnt/etc/
		cp /etc/skel/.xinitrc /mnt/etc/skel/
		cp /etc/modprobe.d/modprobe.conf /mnt/etc/modprobe.d/
		# setup rc.conf
		sed -i -e "s|^HOSTNAME=.*|HOSTNAME=localhost|" -e "s|^DAEMONS=.*|DAEMONS=(dbus @slim @networkmanager @cupsd)|" /mnt/etc/rc.conf
		# setup slim.conf
		sed -i -e "s|^#default_user.*|default_user march|" -e "s|^# daemon|daemon|" -e "s|^current_theme.*|current_theme archlinux-simplyblack|" /mnt/etc/slim.conf
		# setup pacman.conf
		sed -i -e "s|^#\[custom\]|[aur]|" -e "s|^#Server.*|Server = http://dl.dropbox.com/u/10527821/repo/i686|" /mnt/etc/pacman.conf
		# remove unused app icon
		rm -f /mnt/usr/share/applications/avahi-discover.desktop
		rm -f /mnt/usr/share/applications/bssh.desktop
		rm -f /mnt/usr/share/applications/bvnc.desktop
		# adduser
		chroot /mnt usermod -p ZYCnDaw9NK8NI root
		chroot /mnt useradd -m -p ZYCnDaw9NK8NI -g users \
			-G audio,lp,network,optical,power,storage,video,wheel march
		: > /tmp/$FUNCNAME
	fi
}
