#!/bin/bash

sai_config() {
	say "$FUNCNAME: March customized"
	if [ ! -f /tmp/$FUNCNAME ]; then
		# copy march config
		cp /etc/sudoers /mnt/etc/
		cp /etc/modprobe.d/modprobe.conf /mnt/etc/modprobe.d/
		# setup rc.conf
		sed -i -e "s|^HOSTNAME=.*|HOSTNAME=localhost|" -e "s|^DAEMONS=.*|DAEMONS=(dbus @kdm @networkmanager @cupsd)|" /mnt/etc/rc.conf
		# setup pacman.conf
		sed -i -e "s|^#\[custom\]|[aur]|" -e "s|^#Server.*|Server = http://dl.dropbox.com/u/10527821/repo/i686|" /mnt/etc/pacman.conf
		# remove unused app icon
		rm -f /mnt/usr/share/applications/avahi-discover.desktop
		rm -f /mnt/usr/share/applications/bssh.desktop
		rm -f /mnt/usr/share/applications/bvnc.desktop
		# setup scim
		cat >> /mnt/etc/profile <<EOF
export XMODIFIERS=@im=SCIM
export GTK_IM_MODULE="scim"
export QT_IM_MODULE="scim"
scim -d
EOF
		# adduser
		chroot /mnt usermod -p ZYCnDaw9NK8NI root
		chroot /mnt useradd -m -p ZYCnDaw9NK8NI -g users \
			-G audio,lp,network,optical,power,storage,video,wheel march
		: > /tmp/$FUNCNAME
	fi
}
