#!/bin/bash

FS='/tmp/sai_fs'
FSTAB='/tmp/sai_fstab'

: > $FS
: > $FSTAB

source /sai/sai_lib
source /sai/sai_config

sai_start() {
	say "sai will help you install Arch Linux"
}

sai_prepare() {
	say $FUNCNAME

	ask_cfdisk
	ask_mkfs
	ask "sai opens 'vim' to double-check the partitions. Hit 'enter' to continue."
	vim $FS

	# format and create tmp fstab
	prepare_disks
}

sai_install() {
	say $FUNCNAME
	ask "sai opens 'vim' to edit the packages you want to install. Hit 'enter' to continue."
	vim /sai/packages.list

	pacman_install

	# setup fstab asap
	cat $FSTAB >> /mnt/etc/fstab
}

sai_bootloader() {
	say $FUNCNAME
	syslinux-install_update -iam -c /mnt || yell "syslinux can't be installed"

	syslinuxmenu='/mnt/boot/syslinux/syslinux.cfg'
	generate_syslinux_menu
	ask "sai opens 'vim' to edit the bootloader menu. Hit 'enter' to continue."
	vim $syslinuxmenu
}

sai_end() {
	say "sai did its job! you may 'reboot'"
}

sai_start
sai_prepare
sai_install
sai_config
sai_bootloader
sai_end