#!/bin/bash

FS='/tmp/sai_fs'
FSTAB='/tmp/sai_fstab'
LOG='/tmp/sai_log'

# init files
: > $FS
: > $FSTAB
: > $LOG

source /sai/sai_lib
source /sai/sai_config

sai_start() {
	say "sai will help you install Arch Linux"
}

sai_prepare() {
	say $FUNCNAME
	
	umount_dest
	# cfdisk
	avail_disks
	ask "pick a disk to partition? (sai will call cfdisk) "
	cfdisk "/dev/$ans"
	
	# mountpount
	find_partitions
	ask "select a partition for swap? (type 'no' if dont need one) "
	if [ "$ans" != "no" ]; then
		echo "/dev/$ans swap swap" >> $FS
	fi
	ask "select a partition for '/'? "
	echo "/dev/$ans / ext4" >> $FS
	
	ask "select a partition for '/boot'? (type 'no' if dont need one) "
	if [ "$ans" != "no" ]; then
		echo "/dev/$ans /boot ext2" >> $FS
	fi
	
	ask "sai asks you to use 'vim' to double-check everything. Hit 'enter' to continue."
	vim $FS
	
	
	for line in $(cat $FS); do
		PART=$(echo $line | cut -d ' ' -f 1)
		MP=$(echo $line | cut -d ' ' -f 2)
		FSTYPE=$(echo $line | cut -d ' ' -f 3)
		format_disks $PART $MP $FSTYPE
		sleep 1
	done
}

sai_installpkgs() {
	say $FUNCNAME
	ask "sai asks you to edit the packages you want to install. Hit 'enter' to continue."
	vim /sai/packages.list
	chroot_mount
	pacman --root /mnt --noconfirm -Sy "syslinux $(grep -v ^# /sai/packages.list)"
	chroot_umount
}

sai_postconfig() {
	say $FUNCNAME
	chroot /mnt mkinitcpio -p linux
	sort $FSTAB > /mnt/etc/fstab
}

sai_bootloader() {
	say $FUNCNAME
	syslinux-install_update -iam -c /mnt
	syslinuxmenu='/mnt/boot/syslinux/syslinux.cfg'
	generate_syslinux_menu $(search_device '/')
	ask "sai asks you to edit the bootloader menu. Hit 'enter' to continue."
	vim $syslinuxmenu
}

sai_end() {
	say "sai did its job! you may 'reboot'"
}


sai_start
sai_prepare
sai_installpkgs
sai_config
sai_postconfig
sai_bootloader
sai_end
