#!/bin/bash

FS='/tmp/sai_fs'
FSTAB='/tmp/sai_fstab'
LOG='/tmp/sai_log'

# init files
: > $FS
: > $FSTAB
: > $LOG

source /sai/sai_lib

sai_start() {
	say "sai will help you install Arch Linux"
}

sai_prepare() {
	say $FUNCNAME
	
	# cfdisk
	tput rev
	avail_disks
	tput sgr0
	ask "pick a disk to partition? (type 'no' to skip)"
	if [ "$ans" != "no" ]; then
		cfdisk "/dev/$ans"
	fi
	
	# mountpount
	tput rev
	find_partitions
	tput sgr0
	
	ask "select a partition for '/'?"
	echo "/dev/$ans:/:ext4" >> $FS
	
	ask "select a partition for '/boot'? (type 'no' if dont need one)"
	if [ "$ans" != "no" ]; then
		echo "/dev/$ans:/boot:ext2" >> $FS
	fi

	ask "select a partition for swap? (type 'no' if dont need one)"
	if [ "$ans" != "no" ]; then
		echo "/dev/$ans:swap:swap" >> $FS
	fi
	
	ask "sai asks you to use 'vim' to double-check everything. Hit 'enter' to continue."
	vim $FS
	
	prepare_disks
}

sai_installpkgs() {
	say $FUNCNAME
	ask "sai asks you to edit the packages you want to install. Hit 'enter' to continue."
	vim /sai/packages.list
	mkdir -p /mnt/var/lib/pacman
	chroot_mount
	pacman --root /mnt --noconfirm --needed -Sy $(grep -v ^# /sai/packages.list)
	chroot_umount
}

sai_postconfig() {
	say $FUNCNAME
	chroot_mount
	chroot /mnt mkinitcpio -p linux
	chroot_umount
	sort $FSTAB > /mnt/etc/fstab
}

sai_bootloader() {
	say $FUNCNAME
	syslinux-install_update -iam -c /mnt
	syslinuxmenu='/mnt/boot/syslinux/syslinux.cfg'
	generate_syslinux_menu
	ask "sai asks you to edit the bootloader menu. Hit 'enter' to continue."
	vim $syslinuxmenu
}

sai_end() {
	say "sai did its job! you may 'reboot'"
}

source /sai/sai_config

sai_start
sai_prepare
sai_installpkgs
sai_config
sai_postconfig
sai_bootloader
sai_end
