#!/bin/bash

say() {
	tput setaf 4
	echo ":: $1"
	tput sgr0
}

ask() {
	tput setaf 6
	echo -n "=> $1  "
	tput sgr0
	read ans
}

yell() {
	tput setaf 1
	echo -n "!! $1  "
	tput sgr0
	echo "$1" >> $LOG
}

prepare_disks() {
	for line in $(cat $FS); do
		part=$(echo $line | cut -d : -f 1)
		mp=$(echo $line | cut -d : -f 2)
		fstype=$(echo $line | cut -d : -f 3)

		if [ "$fstype" == "swap" ]; then
			mkswap $part
		else
			mkfs.$fstype $part
		fi
		
		mkdir -p /mnt$mp
		mount -t $fstype $part /mnt$mp
		
		echo -n "$part $mp $fstype defaults 0 " >> $FSTAB
		if [ "$fstype" == "swap" ]; then
			echo "0" >> $FSTAB
		else
			echo "1" >> $FSTAB
		fi
	done
}

find_disks() {
	find /sys/block/* -name [hs]d* | cut -d / -f 4
}

find_partitions() {
	find /sys/block/[hs]d*/* -name [hs]d* | cut -d / -f 5
}

disk_capacity() {
	fdisk -l $1 | sed -n '2p' | cut -d ' ' -f 3,4 | sed 's|,$||'
}

avail_disks() {
	for disk in $(find_disks); do
		echo "$disk: $(disk_capacity /dev/$disk)"
	done
}

# chroot_mount()
# prepares target system as a chroot
#
chroot_mount() {
	[ -e /mnt/sys ] || mkdir /mnt/sys
	[ -e /mnt/proc ] || mkdir /mnt/proc
	[ -e /mnt/dev ] || mkdir /mnt/dev
	mount -t sysfs sysfs /mnt/sys
	mount -t proc proc /mnt/proc
	mount -o bind /dev /mnt/dev
}

# chroot_umount()
# tears down chroot in target system
#
chroot_umount() {
	umount /mnt/proc /mnt/sys /mnt/dev
}

search_device() {
	grep ":$1:" $FS | cut -d : -f 1
}

generate_syslinux_menu() {
	rootpart=$(search_device '/')
	sed -i -e "s|root=/dev/sda3|root=$rootpart|g" $syslinuxmenu
}
