#!/bin/bash

FS=/tmp/sai_fs
FSTAB=/tmp/sai_fstab

source /sai/sai_lib
source /sai/sai_config

sai_start() {
	say "sai will help you install Arch Linux"
}

sai_prepare() {
	say $FUNCNAME
	if [[ ! -f /tmp/$FUNCNAME ]]; then
		ask_cfdisk
		ask_mkfs
		ask "sai will double-check the partitions. Hit 'enter' to continue." none
		vim $FS
		: > /tmp/$FUNCNAME

		# format and create tmp fstab
		prepare_disks
	fi
}

sai_install() {
	say $FUNCNAME
	if [[ ! -f /tmp/$FUNCNAME ]]; then
		ask "sai will edit the packages you want to install. Hit 'enter' to continue." none
		vim /sai/packages.list
		pacman_install

		# setup fstab asap
		gen_fstab
		# setup locale to en_US.utf8
		gen_locale
		# setup mirrorlist
		gen_pacman_mirror
		: > /tmp/$FUNCNAME
	fi
}

sai_bootloader() {
	say $FUNCNAME
	if [[ ! -f /tmp/$FUNCNAME ]]; then		
		/mnt/usr/sbin/syslinux-install_update -iam -c /mnt || yell "syslinux can't be installed"
		syslinuxmenu=/mnt/boot/syslinux/syslinux.cfg
		gen_syslinux_menu
		
		: > /tmp/$FUNCNAME
		ask "sai will edit the bootloader menu. Hit 'enter' to continue." none
		vim $syslinuxmenu
	fi
}

sai_end() {
	sai_clean
	say "sai did its job! you may 'reboot'"
}

sai_start
sai_prepare
sai_install
sai_config
sai_bootloader
sai_end
