#!/bin/bash

FS='/tmp/sai_fs'
FSTAB='/tmp/sai_fstab'

source /sai/sai_lib
source /sai/sai_config

sai_start() {
	say "sai will help you install Arch Linux"
}

sai_prepare() {
	say $FUNCNAME
	if [ ! -f /tmp/$FUNCNAME ]; then
		ask_cfdisk	
		ask_mkfs
		ask "sai opens 'vim' to double-check the partitions. Hit 'enter' to continue."
		vim $FS
		: > /tmp/$FUNCNAME

		# format and create tmp fstab
		prepare_disks
	fi
}

sai_install() {
	say $FUNCNAME
	if [ ! -f /tmp/$FUNCNAME ]; then
		ask "sai opens 'vim' to edit the packages you want to install. Hit 'enter' to continue."
		vim /sai/packages.list
		pacman_install

		# setup fstab asap
		cat $FSTAB >> /mnt/etc/fstab
		# setup locale
		sed -i -e "s|^#en_US\.UTF-8|en_US.UTF-8|" /mnt/etc/locale.gen
		chroot /mnt locale-gen
		# setup mirrorlist
		sed -i -e "s|^#\(.*rit\.edu.*\)|\1|g" /mnt/etc/pacman.d/mirrorlist
		: > /tmp/$FUNCNAME
	fi
}

sai_bootloader() {
	say $FUNCNAME
	if [ ! -f /tmp/$FUNCNAME ]; then		
		/mnt/usr/sbin/syslinux-install_update -iam -c /mnt || yell "syslinux can't be installed"
		syslinuxmenu='/mnt/boot/syslinux/syslinux.cfg'
		generate_syslinux_menu
		
		: > /tmp/$FUNCNAME
		ask "sai opens 'vim' to edit the bootloader menu. Hit 'enter' to continue."
		vim $syslinuxmenu
	fi
}

sai_end() {
	say "sai did its job! you may 'reboot'"
}

sai_start
sai_prepare
sai_install
sai_config
sai_bootloader
sai_end