#!/bin/bash

sai_config() {
	say "$FUNCNAME: March customized"
	if [[ ! -f /tmp/$FUNCNAME ]]; then
		# copy march config
		cp -r /sai/etc/ /mnt/
		# mkinitcpio
		chroot /mnt mkinitcpio -p linux
		# adduser
		chroot /mnt usermod -p ZYCnDaw9NK8NI root
		chroot /mnt useradd -m -p ZYCnDaw9NK8NI -g users -G audio,lp,network,optical,power,storage,video,wheel march
		# setup resume
		chroot /mnt suspend-to-disk
		source /usr/lib/powerdown-functions
		sed -i "s|dummy|resume=/dev/disk/by-label/root resume_offset=$(hibernate_offset)|g" /mnt/boot/syslinux/syslinux.cfg
		: > /tmp/$FUNCNAME
		# systemd service
		chroot /mnt systemctl enable kdm.service || true
		chroot /mnt systemctl enable cups.service || true
		chroot /mnt systemctl enable net-auto-wireless.service || true
		chroot /mnt systemctl enable net-auto-wired.service || true
	fi
}
