#!/bin/bash

sai_config() {
	say "$FUNCNAME: March customized"
	if [[ ! -f /tmp/$FUNCNAME ]]; then
		# copy march config
		cp -r /sai/etc/ /mnt/
		# aspm
		sed -i -e 's|\(APPEND root=/dev/disk/by-label/root ro\)|\1 pcie_aspm=force|' /mnt/boot/syslinux/syslinux.cfg
		# adduser
		chroot /mnt usermod -p ZYCnDaw9NK8NI root
		chroot /mnt useradd -m -p ZYCnDaw9NK8NI -g users \
			-G audio,lp,network,optical,power,storage,video,wheel march
		# add march repo
		echo "[march]" >> /mnt/etc/pacman.conf
		echo "Server = http://dl.dropbox.com/u/10527821/repo/i686/" >> /mnt/etc/pacman.conf
		: > /tmp/$FUNCNAME
	fi
}
