#!/bin/bash

sai_config() {
	say "$FUNCNAME: March customized"
	if [[ ! -f /tmp/$FUNCNAME ]]; then
		# copy march config
		cp -r /sai/etc/ /mnt/
		# setup rc.conf
		sed -i -e 's|^HARDWARECLOCK=.*|HARDWARECLOCK="localtime"|' \
		-e 's|^HOSTNAME=.*|HOSTNAME="localhost"|' \
		-e 's|^DAEMONS=.*|DAEMONS=(dbus @alsa @wicd @cupsd)|' /mnt/etc/rc.conf
		# mirror & locale set in sai
		# adduser
		chroot /mnt usermod -p ZYCnDaw9NK8NI root
		chroot /mnt useradd -m -p ZYCnDaw9NK8NI -g users \
			-G audio,lp,network,optical,power,storage,video,wheel march
		: > /tmp/$FUNCNAME
	fi
}
