#!/bin/bash

# setup mirrorlist
curl -o /etc/pacman.d/mirrorlist 'https://www.archlinux.org/mirrorlist/?country=all&protocol=http&use_mirror_status=on'
sed -i "s/#Server/Server/g" /etc/pacman.d/mirrorlist

# sai
/sai/customize

# remove unused manual
rm -rf /usr/share/{man,doc,gtk-doc,licenses,info,gtk-2.0,gtk-3.0}/

# remove static library
find / -name "*.a" -exec rm -f {} +

