#!/bin/bash

# march overlay
march-reset
chattr +i /etc/resolv.conf

# mkinitcpio
mkinitcpio -p linux

# setup vundle
git clone https://github.com/gmarik/Vundle.vim.git /etc/skel/.vim/bundle/Vundle.vim

# adduser
usermod -p ZYCnDaw9NK8NI root
useradd -m -p ZYCnDaw9NK8NI -G wheel march

# setup vundle plugins
runuser -u march vim +PluginInstall +qall
# YCM
cd /home/march/.vim/bundle/YouCompleteMe
runuser -u march ./install.sh

# setup locale
sed -i -e 's|^#\(en_US\.UTF-8\)|\1|' /etc/locale.gen
locale-gen

# systemd service
systemctl enable multi-user.target org.cups.cupsd.service cups-browsed.service zramswap.service connman.service connman-vpn.service psd.service tlp.service tlp-sleep.service ldm.service
