#!/bin/bash

sai_config() {
	say "$FUNCNAME: March"
	if [[ ! -f /tmp/$FUNCNAME ]]; then
		# mirrorlist is updated by sai

		/sai/customize

		# setup boot
		sed -i "s|dummy|%ARCHISO_OPTIONS%|g" /boot/syslinux/syslinux.cfg

		: > /tmp/$FUNCNAME
	fi
}
