#!/bin/bash

# change permission
chmod 440 /etc/sudoers
chmod 755 /install
# remove unused manual
rm -rf /usr/share/man/
rm -rf /usr/share/doc/
rm -rf /usr/share/gtk-doc/
rm -rf /usr/share/licenses/
rm -rf /usr/share/info/
rm -rf /usr/share/gtk-2.0/
rm -rf /usr/share/gtk-3.0/
# setup mirrorlist
sed -i "s/#Server/Server/g" /etc/pacman.d/mirrorlist
# adduser
usermod -p ZYCnDaw9NK8NI root
useradd -m -p ZYCnDaw9NK8NI -g users -G audio,lp,network,optical,power,storage,video,wheel march

# setup locale
sed -i -e 's|^#\(en_US\.UTF-8\)|\1|' /etc/locale.gen
locale-gen

# systemd service
systemctl enable multi-user.target cups.service netcfg.service
