#!/bin/bash

# march overlay
march-reset

# change permission
chmod 440 /etc/sudoers
chmod 755 /install

# remove unused manual
rm -rf /usr/share/man/
rm -rf /usr/share/doc/
rm -rf /usr/share/gtk-doc/
rm -rf /usr/share/licenses/
rm -rf /usr/share/info/
rm -rf /usr/share/gtk-2.0/
rm -rf /usr/share/gtk-3.0/

# remove static library
find / -name "*.a" -exec rm -f {} +

# setup mirrorlist
wget -O /etc/pacman.d/mirrorlist 'https://www.archlinux.org/mirrorlist/?country=all&protocol=http&use_mirror_status=on'
sed -i "s/#Server/Server/g" /etc/pacman.d/mirrorlist

# setup vundle
git clone https://github.com/gmarik/vundle.git /etc/skel/.vim/bundle/vundle

# adduser
usermod -p ZYCnDaw9NK8NI root
useradd -m -p ZYCnDaw9NK8NI -g users -G audio,lp,network,optical,power,storage,video,wheel march

# setup vundle plugins
runuser -u march vim +BundleInstall +qall

# setup timezone
ln -s /usr/share/zoneinfo/America/Los_Angeles /etc/localtime

# setup locale
sed -i -e 's|^#\(en_US\.UTF-8\)|\1|' /etc/locale.gen
locale-gen

# systemd service
systemctl enable multi-user.target cups.service connman.service connman-vpn.service zramswap.service
